mutation {
  insertEnglishBeginner: language_insert(data: { name: "EnglishBeginner" })
  insertEnglishIntermediate: language_insert(data: { name: "EnglishIntermediate" })
  insertEnglishConversational: language_insert(data: { name: "EnglishConversational" })
  insertEnglishFluent: language_insert(data: { name: "EnglishFluent" })

  insertSpanishBeginner: language_insert(data: { name: "SpanishBeginner" })
  insertSpanishIntermediate: language_insert(data: { name: "SpanishIntermediate" })
  insertSpanishConversational: language_insert(data: { name: "SpanishConversational" })
  insertSpanishFluent: language_insert(data: { name: "SpanishFluent" })

  insertMandarinBeginner: language_insert(data: { name: "MandarinBeginner" })
  insertMandarinIntermediate: language_insert(data: { name: "MandarinIntermediate" })
  insertMandarinConversational: language_insert(data: { name: "MandarinConversational" })
  insertMandarinFluent: language_insert(data: { name: "MandarinFluent" })

  insertFrenchBeginner: language_insert(data: { name: "FrenchBeginner" })
  insertFrenchIntermediate: language_insert(data: { name: "FrenchIntermediate" })
  insertFrenchConversational: language_insert(data: { name: "FrenchConversational" })
  insertFrenchFluent: language_insert(data: { name: "FrenchFluent" })

  insertArabicBeginner: language_insert(data: { name: "ArabicBeginner" })
  insertArabicIntermediate: language_insert(data: { name: "ArabicIntermediate" })
  insertArabicConversational: language_insert(data: { name: "ArabicConversational" })
  insertArabicFluent: language_insert(data: { name: "ArabicFluent" })

  insertGermanBeginner: language_insert(data: { name: "GermanBeginner" })
  insertGermanIntermediate: language_insert(data: { name: "GermanIntermediate" })
  insertGermanConversational: language_insert(data: { name: "GermanConversational" })
  insertGermanFluent: language_insert(data: { name: "GermanFluent" })

  insertJapaneseBeginner: language_insert(data: { name: "JapaneseBeginner" })
  insertJapaneseIntermediate: language_insert(data: { name: "JapaneseIntermediate" })
  insertJapaneseConversational: language_insert(data: { name: "JapaneseConversational" })
  insertJapaneseFluent: language_insert(data: { name: "JapaneseFluent" })

  insertRussianBeginner: language_insert(data: { name: "RussianBeginner" })
  insertRussianIntermediate: language_insert(data: { name: "RussianIntermediate" })
  insertRussianConversational: language_insert(data: { name: "RussianConversational" })
  insertRussianFluent: language_insert(data: { name: "RussianFluent" })

  insertPortugueseBeginner: language_insert(data: { name: "PortugueseBeginner" })
  insertPortugueseIntermediate: language_insert(data: { name: "PortugueseIntermediate" })
  insertPortugueseConversational: language_insert(data: { name: "PortugueseConversational" })
  insertPortugueseFluent: language_insert(data: { name: "PortugueseFluent" })

  insertHindiBeginner: language_insert(data: { name: "HindiBeginner" })
  insertHindiIntermediate: language_insert(data: { name: "HindiIntermediate" })
  insertHindiConversational: language_insert(data: { name: "HindiConversational" })
  insertHindiFluent: language_insert(data: { name: "HindiFluent" })

  insertItalianBeginner: language_insert(data: { name: "ItalianBeginner" })
  insertItalianIntermediate: language_insert(data: { name: "ItalianIntermediate" })
  insertItalianConversational: language_insert(data: { name: "ItalianConversational" })
  insertItalianFluent: language_insert(data: { name: "ItalianFluent" })

  insertKoreanBeginner: language_insert(data: { name: "KoreanBeginner" })
  insertKoreanIntermediate: language_insert(data: { name: "KoreanIntermediate" })
  insertKoreanConversational: language_insert(data: { name: "KoreanConversational" })
  insertKoreanFluent: language_insert(data: { name: "KoreanFluent" })

  insertDutchBeginner: language_insert(data: { name: "DutchBeginner" })
  insertDutchIntermediate: language_insert(data: { name: "DutchIntermediate" })
  insertDutchConversational: language_insert(data: { name: "DutchConversational" })
  insertDutchFluent: language_insert(data: { name: "DutchFluent" })

  insertSwedishBeginner: language_insert(data: { name: "SwedishBeginner" })
  insertSwedishIntermediate: language_insert(data: { name: "SwedishIntermediate" })
  insertSwedishConversational: language_insert(data: { name: "SwedishConversational" })
  insertSwedishFluent: language_insert(data: { name: "SwedishFluent" })

  insertTurkishBeginner: language_insert(data: { name: "TurkishBeginner" })
  insertTurkishIntermediate: language_insert(data: { name: "TurkishIntermediate" })
  insertTurkishConversational: language_insert(data: { name: "TurkishConversational" })
  insertTurkishFluent: language_insert(data: { name: "TurkishFluent" })

  insertVietnameseBeginner: language_insert(data: { name: "VietnameseBeginner" })
  insertVietnameseIntermediate: language_insert(data: { name: "VietnameseIntermediate" })
  insertVietnameseConversational: language_insert(data: { name: "VietnameseConversational" })
  insertVietnameseFluent: language_insert(data: { name: "VietnameseFluent" })

  insertPolishBeginner: language_insert(data: { name: "PolishBeginner" })
  insertPolishIntermediate: language_insert(data: { name: "PolishIntermediate" })
  insertPolishConversational: language_insert(data: { name: "PolishConversational" })
  insertPolishFluent: language_insert(data: { name: "PolishFluent" })

  insertThaiBeginner: language_insert(data: { name: "ThaiBeginner" })
  insertThaiIntermediate: language_insert(data: { name: "ThaiIntermediate" })
  insertThaiConversational: language_insert(data: { name: "ThaiConversational" })
  insertThaiFluent: language_insert(data: { name: "ThaiFluent" })

  insertIndonesianBeginner: language_insert(data: { name: "IndonesianBeginner" })
  insertIndonesianIntermediate: language_insert(data: { name: "IndonesianIntermediate" })
  insertIndonesianConversational: language_insert(data: { name: "IndonesianConversational" })
  insertIndonesianFluent: language_insert(data: { name: "IndonesianFluent" })

  insertGreekBeginner: language_insert(data: { name: "GreekBeginner" })
  insertGreekIntermediate: language_insert(data: { name: "GreekIntermediate" })
  insertGreekConversational: language_insert(data: { name: "GreekConversational" })
  insertGreekFluent: language_insert(data: { name: "GreekFluent" })

  insertCzechBeginner: language_insert(data: { name: "CzechBeginner" })
  insertCzechIntermediate: language_insert(data: { name: "CzechIntermediate" })
  insertCzechConversational: language_insert(data: { name: "CzechConversational" })
  insertCzechFluent: language_insert(data: { name: "CzechFluent" })

  insertHebrewBeginner: language_insert(data: { name: "HebrewBeginner" })
  insertHebrewIntermediate: language_insert(data: { name: "HebrewIntermediate" })
  insertHebrewConversational: language_insert(data: { name: "HebrewConversational" })
  insertHebrewFluent: language_insert(data: { name: "HebrewFluent" })

  insertNorwegianBeginner: language_insert(data: { name: "NorwegianBeginner" })
  insertNorwegianIntermediate: language_insert(data: { name: "NorwegianIntermediate" })
  insertNorwegianConversational: language_insert(data: { name: "NorwegianConversational" })
  insertNorwegianFluent: language_insert(data: { name: "NorwegianFluent" })

  insertDanishBeginner: language_insert(data: { name: "DanishBeginner" })
  insertDanishIntermediate: language_insert(data: { name: "DanishIntermediate" })
  insertDanishConversational: language_insert(data: { name: "DanishConversational" })
  insertDanishFluent: language_insert(data: { name: "DanishFluent" })

  insertFinnishBeginner: language_insert(data: { name: "FinnishBeginner" })
  insertFinnishIntermediate: language_insert(data: { name: "FinnishIntermediate" })
  insertFinnishConversational: language_insert(data: { name: "FinnishConversational" })
  insertFinnishFluent: language_insert(data: { name: "FinnishFluent" })

  insertHungarianBeginner: language_insert(data: { name: "HungarianBeginner" })
  insertHungarianIntermediate: language_insert(data: { name: "HungarianIntermediate" })
  insertHungarianConversational: language_insert(data: { name: "HungarianConversational" })
  insertHungarianFluent: language_insert(data: { name: "HungarianFluent" })

  insertRomanianBeginner: language_insert(data: { name: "RomanianBeginner" })
  insertRomanianIntermediate: language_insert(data: { name: "RomanianIntermediate" })
  insertRomanianConversational: language_insert(data: { name: "RomanianConversational" })
  insertRomanianFluent: language_insert(data: { name: "RomanianFluent" })

  insertBulgarianBeginner: language_insert(data: { name: "BulgarianBeginner" })
  insertBulgarianIntermediate: language_insert(data: { name: "BulgarianIntermediate" })
  insertBulgarianConversational: language_insert(data: { name: "BulgarianConversational" })
  insertBulgarianFluent: language_insert(data: { name: "BulgarianFluent" })

  insertUkrainianBeginner: language_insert(data: { name: "UkrainianBeginner" })
  insertUkrainianIntermediate: language_insert(data: { name: "UkrainianIntermediate" })
  insertUkrainianConversational: language_insert(data: { name: "UkrainianConversational" })
  insertUkrainianFluent: language_insert(data: { name: "UkrainianFluent" })

  insertMalayBeginner: language_insert(data: { name: "MalayBeginner" })
  insertMalayIntermediate: language_insert(data: { name: "MalayIntermediate" })
  insertMalayConversational: language_insert(data: { name: "MalayConversational" })
  insertMalayFluent: language_insert(data: { name: "MalayFluent" })

  insertFilipinoBeginner: language_insert(data: { name: "FilipinoBeginner" })
  insertFilipinoIntermediate: language_insert(data: { name: "FilipinoIntermediate" })
  insertFilipinoConversational: language_insert(data: { name: "FilipinoConversational" })
  insertFilipinoFluent: language_insert(data: { name: "FilipinoFluent" })

  insertSwahiliBeginner: language_insert(data: { name: "SwahiliBeginner" })
  insertSwahiliIntermediate: language_insert(data: { name: "SwahiliIntermediate" })
  insertSwahiliConversational: language_insert(data: { name: "SwahiliConversational" })
  insertSwahiliFluent: language_insert(data: { name: "SwahiliFluent" })

  insertBengaliBeginner: language_insert(data: { name: "BengaliBeginner" })
  insertBengaliIntermediate: language_insert(data: { name: "BengaliIntermediate" })
  insertBengaliConversational: language_insert(data: { name: "BengaliConversational" })
  insertBengaliFluent: language_insert(data: { name: "BengaliFluent" })

  insertPunjabiBeginner: language_insert(data: { name: "PunjabiBeginner" })
  insertPunjabiIntermediate: language_insert(data: { name: "PunjabiIntermediate" })
  insertPunjabiConversational: language_insert(data: { name: "PunjabiConversational" })
  insertPunjabiFluent: language_insert(data: { name: "PunjabiFluent" })

  insertTamilBeginner: language_insert(data: { name: "TamilBeginner" })
  insertTamilIntermediate: language_insert(data: { name: "TamilIntermediate" })
  insertTamilConversational: language_insert(data: { name: "TamilConversational" })
  insertTamilFluent: language_insert(data: { name: "TamilFluent" })

  insertTeluguBeginner: language_insert(data: { name: "TeluguBeginner" })
  insertTeluguIntermediate: language_insert(data: { name: "TeluguIntermediate" })
  insertTeluguConversational: language_insert(data: { name: "TeluguConversational" })
  insertTeluguFluent: language_insert(data: { name: "TeluguFluent" })

  insertMarathiBeginner: language_insert(data: { name: "MarathiBeginner" })
  insertMarathiIntermediate: language_insert(data: { name: "MarathiIntermediate" })
  insertMarathiConversational: language_insert(data: { name: "MarathiConversational" })
  insertMarathiFluent: language_insert(data: { name: "MarathiFluent" })

  insertGujaratiBeginner: language_insert(data: { name: "GujaratiBeginner" })
  insertGujaratiIntermediate: language_insert(data: { name: "GujaratiIntermediate" })
  insertGujaratiConversational: language_insert(data: { name: "GujaratiConversational" })
  insertGujaratiFluent: language_insert(data: { name: "GujaratiFluent" })

  insertUrduBeginner: language_insert(data: { name: "UrduBeginner" })
  insertUrduIntermediate: language_insert(data: { name: "UrduIntermediate" })
  insertUrduConversational: language_insert(data: { name: "UrduConversational" })
  insertUrduFluent: language_insert(data: { name: "UrduFluent" })

  insertPersianBeginner: language_insert(data: { name: "PersianBeginner" })
  insertPersianIntermediate: language_insert(data: { name: "PersianIntermediate" })
  insertPersianConversational: language_insert(data: { name: "PersianConversational" })
  insertPersianFluent: language_insert(data: { name: "PersianFluent" })

  insertSlovakBeginner: language_insert(data: { name: "SlovakBeginner" })
  insertSlovakIntermediate: language_insert(data: { name: "SlovakIntermediate" })
  insertSlovakConversational: language_insert(data: { name: "SlovakConversational" })
  insertSlovakFluent: language_insert(data: { name: "SlovakFluent" })

  insertCatalanBeginner: language_insert(data: { name: "CatalanBeginner" })
  insertCatalanIntermediate: language_insert(data: { name: "CatalanIntermediate" })
  insertCatalanConversational: language_insert(data: { name: "CatalanConversational" })
  insertCatalanFluent: language_insert(data: { name: "CatalanFluent" })

  insertLatvianBeginner: language_insert(data: { name: "LatvianBeginner" })
  insertLatvianIntermediate: language_insert(data: { name: "LatvianIntermediate" })
  insertLatvianConversational: language_insert(data: { name: "LatvianConversational" })
  insertLatvianFluent: language_insert(data: { name: "LatvianFluent" })

  insertLithuanianBeginner: language_insert(data: { name: "LithuanianBeginner" })
  insertLithuanianIntermediate: language_insert(data: { name: "LithuanianIntermediate" })
  insertLithuanianConversational: language_insert(data: { name: "LithuanianConversational" })
  insertLithuanianFluent: language_insert(data: { name: "LithuanianFluent" })

  insertEstonianBeginner: language_insert(data: { name: "EstonianBeginner" })
  insertEstonianIntermediate: language_insert(data: { name: "EstonianIntermediate" })
  insertEstonianConversational: language_insert(data: { name: "EstonianConversational" })
  insertEstonianFluent: language_insert(data: { name: "EstonianFluent" })

  insertSlovenianBeginner: language_insert(data: { name: "SlovenianBeginner" })
  insertSlovenianIntermediate: language_insert(data: { name: "SlovenianIntermediate" })
  insertSlovenianConversational: language_insert(data: { name: "SlovenianConversational" })
  insertSlovenianFluent: language_insert(data: { name: "SlovenianFluent" })

  insertCroatianBeginner: language_insert(data: { name: "CroatianBeginner" })
  insertCroatianIntermediate: language_insert(data: { name: "CroatianIntermediate" })
  insertCroatianConversational: language_insert(data: { name: "CroatianConversational" })
  insertCroatianFluent: language_insert(data: { name: "CroatianFluent" })

  insertSerbianBeginner: language_insert(data: { name: "SerbianBeginner" })
  insertSerbianIntermediate: language_insert(data: { name: "SerbianIntermediate" })
  insertSerbianConversational: language_insert(data: { name: "SerbianConversational" })
  insertSerbianFluent: language_insert(data: { name: "SerbianFluent" })

  insertIcelandicBeginner: language_insert(data: { name: "IcelandicBeginner" })
  insertIcelandicIntermediate: language_insert(data: { name: "IcelandicIntermediate" })
  insertIcelandicConversational: language_insert(data: { name: "IcelandicConversational" })
  insertIcelandicFluent: language_insert(data: { name: "IcelandicFluent" })

  insertBasqueBeginner: language_insert(data: { name: "BasqueBeginner" })
  insertBasqueIntermediate: language_insert(data: { name: "BasqueIntermediate" })
  insertBasqueConversational: language_insert(data: { name: "BasqueConversational" })
  insertBasqueFluent: language_insert(data: { name: "BasqueFluent" })

  insertIrishBeginner: language_insert(data: { name: "IrishBeginner" })
  insertIrishIntermediate: language_insert(data: { name: "IrishIntermediate" })
  insertIrishConversational: language_insert(data: { name: "IrishConversational" })
  insertIrishFluent: language_insert(data: { name: "IrishFluent" })

  insertScottishGaelicBeginner: language_insert(data: { name: "ScottishGaelicBeginner" })
  insertScottishGaelicIntermediate: language_insert(data: { name: "ScottishGaelicIntermediate" })
  insertScottishGaelicConversational: language_insert(data: { name: "ScottishGaelicConversational" })
  insertScottishGaelicFluent: language_insert(data: { name: "ScottishGaelicFluent" })

  insertWelshBeginner: language_insert(data: { name: "WelshBeginner" })
  insertWelshIntermediate: language_insert(data: { name: "WelshIntermediate" })
  insertWelshConversational: language_insert(data: { name: "WelshConversational" })
  insertWelshFluent: language_insert(data: { name: "WelshFluent" })
}